name: Gazette Continuous Integration

# TODO: change to pull_request once things are working
on:
  push: {}
  release:
    types: [ created, published, edited, prereleased ]

jobs:
  debug:
    runs-on: ubuntu-18.04
    steps:
      - name: 'Print event info'
        run: |
          echo event_name=${{ github.event_name }};
          echo "Event Json: " 
          echo ${{ toJson(github.event) }}
          
  test:
    runs-on: ubuntu-18.04
    needs: debug
    container:
      image: gazette/ci-builder:20200421
      env:
        # TODO: see which of these env vars we still need on GH Actions
        # Instruct the go tool to place the module cache under the working
        # directory (~/project)
        GOPATH: /root/project/.build/go-path
        # RocksDB version to build. Keep in sync with mk/config.mk
        # Also be sure to update the save_cache step below.
        ROCKSDB_VERSION: 6.7.3
        # `nproc` on CircleCI docker runners returns the number of host cores,
        # not provisioned cores (eg, 36 cores when only 2 are available).
        NPROC: 2
        # Same issue with GOMAXPROCS.
        GOMAXPROCS: 2

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'RocksDB Cache'
        uses: actions/cache@v2
        with:
          key: rocksdb-${{ hashFiles('.build/rocksdb-v*/librocksdb.so') }}
          path: ".build/rocksdb-v${{ env.ROCKSDB_VERSION }}"

      - name: 'Go Module Cache'
        uses: actions/cache@v2
        with:
          key: go-mod-v1-${{ hashFiles('go.sum') }}
          path: ".build/go-path/pkg"
          # If we don't have a cached directory that matches the hash exactly,
          # then this will allow a non-matching directory to be pulled in. This is safe
          # because go will use its own finer-grained cache invalidation logic
          restore-keys: "go-mod-v1-"

      - name: 'Install'
        run: "make go-install"

      - name: 'Test'
        run: "make go-test-ci"

  release:
    runs-on: ubuntu-18.04
    needs: debug
    if: ${{ github.event_name }} == 'release'
    container:
      image: gazette/ci-builder:20200421
      env:
        # TODO: see which of these env vars we still need on GH Actions
        # Instruct the go tool to place the module cache under the working
        # directory (~/project)
        GOPATH: /root/project/.build/go-path
        # RocksDB version to build. Keep in sync with mk/config.mk
        # Also be sure to update the save_cache step below.
        ROCKSDB_VERSION: 6.7.3
        # `nproc` on CircleCI docker runners returns the number of host cores,
        # not provisioned cores (eg, 36 cores when only 2 are available).
        NPROC: 2
        # Same issue with GOMAXPROCS.
        GOMAXPROCS: 2

    steps:
      - name: 'Placeholder'
        run: |
          echo -e "*************** \n\n RUNNING RELEASE \n\n *********************"

