name: Gazette Continuous Integration

# TODO: change to pull_request once things are working
on: push
env:
  # TODO: see which of these env vars we still need on GH Actions
  # Instruct the go tool to place the module cache under the working
  # directory (~/project)
  GOPATH: /root/project/.build/go-path
  # RocksDB version to build. Keep in sync with mk/config.mk
  # Also be sure to update the save_cache step below.
  ROCKSDB_VERSION: 6.7.3
  # `nproc` on CircleCI docker runners returns the number of host cores,
  # not provisioned cores (eg, 36 cores when only 2 are available).
  NPROC: 2
  # Same issue with GOMAXPROCS.
  GOMAXPROCS: 2

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install'
        uses: './mk/'
        with:
          make-target: 'go-install'
      - name: 'Test'
        uses: './mk/'
        with:
          make-target: 'go-test-ci'
